### PR TITLE
edits + remove fragile tiles for now

### PR DESCRIPTION
**Pull request by recursiveforte**

### CODE REVIEW

**Comment by SerenityUX** [comment]
Please resubmit w/o Markdown comments.

**Comment by recursiveforte** [comment]
I just commented out a temporary removal of part of the Jam - the comment is intentional, and I eventually plan to uncomment that section.

**Comment by SerenityUX** [comment]
I believe comments break mdx-remote. If I merge, I believe the build will fail.

**Comment by recursiveforte** [comment]
Ah, ok. Removed.

**Pull request merged**
